//! The names the galaxy does not have to store.
//!
//! **97.3 % of a galaxy's system names are a function of the system's
//! address.** Measured over `.index/full` — 200,071,629 names — 194,667,563
//! of them are spelled exactly by the arithmetic here plus the sector
//! dictionary beside it. A name that agrees with what this derives does not
//! have to be written down at all: `text.bin` holds 3.94 GB of names and
//! 136 MB of them are names this cannot spell.
//!
//! ## What an address carries
//!
//! [`elite_journal::Boxel`] holds that half: a `SystemAddress` packs the
//! system's mass class, its sector on the galaxy's 1,280 ly grid, the
//! boxel inside that sector and the system's index inside the boxel, and a
//! procedural name spells the same place back — `PRAEA EUQ YE-Q D5-0`. The
//! layout and the spelling are facts about the game and are written down
//! there, beside the events they arrive in.
//!
//! What is here is the other half, which is *not* a fact about the game:
//! **the sector's name**. Frontier generates it, and no arithmetic in this
//! crate reproduces the generator — so the dictionary is **learned** from a
//! galaxy somebody imported (`galos index sectors`) and compiled in. 11,662
//! sectors, 192 KB, and the join of the two halves is [`name_of`].
//!
//! ## What it cannot spell, and why that is safe
//!
//! Two populations, both measured:
//!
//! - **Names people gave** — 151,463 of them, `HD 225160`, `CYGNI X-3`.
//!   They are not procedural and nothing here claims them.
//! - **Frontier's hand-authored regions** — `COL 285 SECTOR`, `IC 2944
//!   SECTOR`, the nebulae: 5,252,594 rows. A region is a sphere laid over
//!   the grid, spanning up to eight sectors, and its boxels are numbered
//!   from the region's own origin rather than the grid's. So the sector
//!   dictionary deliberately **does not hold them**: a name that claimed
//!   more than one sector coordinate is left out of the dictionary, and
//!   every system under one is stored.
//!
//! Which is what makes the scheme safe rather than clever: the caller
//! derives a name, compares it with the one reported, and stores the name
//! whenever the two differ. A derivation that is wrong is a name that gets
//! written down, not a name that gets lost. And a system whose name arrives
//! later is one stored name over a derived one, which is the overlay this
//! table already has.

use crate::SystemName;
use elite_journal::Boxel;
use std::sync::LazyLock;

/// The sector dictionary: a packed sector coordinate and the name of it.
///
/// Generated by `galos index sectors` from a built directory, and compiled
/// in rather than published: it is 11,662 sectors and 192 KB, it is the
/// same for every galaxy, and a derivation that needed a file could not be
/// done by a database writer with no index directory to read.
///
/// Sorted by key, which is what makes the parse below a sorted vector
/// without a sort. A plain `key,name` a line and no quoting: every sector
/// name Frontier generates is `[A-Z0-9 ]` — measured over all 11,662, no
/// commas and no quotes — and `the_dictionary_is_read` asserts that, so a
/// name that ever arrived with a comma in it would fail the test rather
/// than split a row in half.
const SECTORS: &str = include_str!("../../data/sectors.csv");

/// How many bits of the key each sector axis takes: x and z reach 127, y
/// reaches 63, which is the galaxy's own grid.
const SECTOR_BITS: [u32; 3] = [7, 6, 7];

/// A sector's coordinates as one number, which is how the dictionary keys
/// them.
///
/// This crate's own encoding rather than anything the game writes — twenty
/// bits of the grid, packed x, y, z — so it lives here with the file it
/// keys and not beside [`Boxel`], which holds only what an address says.
pub fn sector_key(sector: [u8; 3]) -> u32 {
    (u32::from(sector[0]) << (SECTOR_BITS[1] + SECTOR_BITS[2]))
        | (u32::from(sector[1]) << SECTOR_BITS[2])
        | u32::from(sector[2])
}

/// The sector coordinates a [`sector_key`] stands for.
fn sector_of(key: u32) -> [u8; 3] {
    [
        (key >> (SECTOR_BITS[1] + SECTOR_BITS[2])) as u8,
        ((key >> SECTOR_BITS[2]) & 0x3F) as u8,
        (key & 0x7F) as u8,
    ]
}

/// The dictionary, parsed once off the text compiled into the binary.
struct Sectors {
    /// Every sector, by key, in the file's own ascending order.
    by_key: Vec<(u32, &'static str)>,
    /// The same rows by name, for resolving a name to an address.
    by_name: Vec<(&'static str, u32)>,
}

/// The sector dictionary, parsed on the first ask.
///
/// Two sorted vectors over the compiled-in text: nothing is copied, the
/// names being `&'static str` into the binary itself, and 11,662 rows is
/// tens of microseconds to parse. A `HashMap` would cost the same lookups
/// an allocation apiece to build and lose the by-name order a search wants.
static SECTOR_TABLE: LazyLock<Sectors> = LazyLock::new(|| {
    let mut by_key: Vec<(u32, &'static str)> = SECTORS
        .lines()
        .filter_map(|line| {
            let (key, name) = line.split_once(',')?;
            Some((key.parse().ok()?, name))
        })
        .collect();
    by_key.sort_unstable_by_key(|(key, _)| *key);
    let mut by_name: Vec<(&'static str, u32)> =
        by_key.iter().map(|(key, name)| (*name, *key)).collect();
    by_name.sort_unstable();
    Sectors { by_key, by_name }
});

/// How many sectors the dictionary holds.
#[cfg(test)]
pub(crate) fn sector_count() -> usize {
    SECTOR_TABLE.by_key.len()
}

/// Every sector the dictionary holds, by key, ascending.
///
/// For whoever is regenerating the file: the one property it has to keep is
/// that an entry is added and never changed or dropped, since a name was
/// left unwritten because this spelled it. See `galos index sectors`.
pub fn sectors() -> impl Iterator<Item = (u32, &'static str)> {
    SECTOR_TABLE.by_key.iter().copied()
}

/// The name of the sector at `key`, or [`None`] where none is known.
///
/// [`None`] is the ordinary answer for unexplored space and for the
/// hand-authored regions, which are deliberately absent — see the module
/// header.
pub fn sector_at(key: u32) -> Option<&'static str> {
    let held = &*SECTOR_TABLE;
    held.by_key
        .binary_search_by_key(&key, |(key, _)| *key)
        .ok()
        .map(|at| held.by_key[at].1)
}

/// The sector coordinates of the sector named `name`, upper case.
pub(crate) fn sector_named(name: &str) -> Option<[u8; 3]> {
    let held = &*SECTOR_TABLE;
    let at =
        held.by_name.binary_search_by_key(&name, |(name, _)| *name).ok()?;
    Some(sector_of(held.by_name[at].1))
}

/// The name `address` spells, or [`None`] where nothing spells it.
///
/// [`None`] where the address's sector is not in the dictionary, which is
/// unexplored space and every hand-authored region. A caller comparing this
/// against a reported name gets the whole rule: equal, and the name need
/// not be stored; anything else, and it must be.
pub fn name_of(address: i64) -> Option<SystemName> {
    let boxel = Boxel::of(address);
    let sector = sector_at(sector_key(boxel.sector))?;
    // `new` takes the string it is handed and folds it in place, and the
    // pieces are upper already, so this is the one allocation the format
    // itself needs and no copy on top of it.
    Some(SystemName::new(format!("{sector} {}", boxel.tail())))
}

/// The address `name` spells, or [`None`] where it spells none.
///
/// The inverse of [`name_of`], which is what makes a name resolvable
/// without a table: a procedural name carries its own address. Checked
/// rather than assumed — [`Boxel::address`] refuses a name spelling
/// coordinates no address holds — and confirmed by round-tripping it, so a
/// name that resolves here resolves to the system that bears it.
pub fn address_of(name: &str) -> Option<i64> {
    let (head, last) = name.rsplit_once(' ')?;
    let (sector, code) = head.rsplit_once(' ')?;
    let at = sector_named(sector)?;
    let boxel = Boxel::spelled(&format!("{code} {last}"), at)?;
    let address = boxel.address()?;
    // The one check that makes this safe to answer a lookup with: the
    // address has to spell the name back.
    (Boxel::of(address) == boxel).then_some(address)
}

/// Whether `name` is what [`name_of`] spells for `address`.
///
/// The question a writer asks before storing a name.
pub fn spells(address: i64, name: &str) -> bool {
    name_of(address).is_some_and(|held| held == *name)
}

/// How many letters of a *word* may be wrong before it says nothing
///
/// `EXACTLY_UNDER` is about a whole sector name; a word of one is three
/// to six letters, and the bound has to be read against that length or it
/// answers with the vocabulary. One edit on three letters reaches a quarter
/// of the alphabet — `EQU` is one from `EQ-G`, `ECU`, `EQZ` — so three
/// letters are matched exactly and the slack opens with the word:
///
/// | letters | edits |
/// |---|---|
/// | under four | 0 |
/// | four or five | 1 |
/// | six or more | [`NEAREST`] |
pub fn slack(word: &str) -> usize {
    match word.len() {
        0..=3 => 0,
        4..=5 => 1,
        _ => NEAREST,
    }
}

/// Whether `word` matches `held`: at its start, or near enough
///
/// The one rule a query's word is matched by, wherever it is matched — the
/// sector vocabulary here, and the rows a caller sieves behind it. A prefix
/// counts because that is what a search is; the edits are [`slack`]'s.
pub(crate) fn matches_word(word: &str, held: &str) -> bool {
    edits_to(word, held).is_some()
}

/// The same, answering how many letters are wrong
///
/// Nought for a prefix, which is what a search is, and otherwise the edit
/// distance — so a caller with more answers than room offers the nearest
/// rather than whichever it swept first.
pub(crate) fn edits_to(word: &str, held: &str) -> Option<usize> {
    if held.starts_with(word) {
        return Some(0);
    }
    // **Coordinates are never fuzzed.** A wrong letter in `YE-Q` is a
    // different boxel rather than a near miss, and the boxels are all
    // real: fuzzing it answered `YE-Q D5-0` with `TE-Q D5-0`, a place
    // the reader did not ask about and cannot tell from the one they did.
    if is_coordinate(word) {
        return None;
    }
    within(word.as_bytes(), held.as_bytes(), slack(word))
}

/// The sectors holding the most of `words`, the most first, at most `limit`
///
/// **What answers a query whose words are out of order.** A derived name is
/// a sector and then coordinates, so a reader typing `EUQ PRAEA` — or the
/// sector of a place they have been and the boxel code off a screenshot —
/// is naming the sector in pieces. A sector matching two of the words is
/// offered before one matching a single word, and a word that matches no
/// sector at all is left to the caller to check against the coordinates.
///
/// `near` is where the reader is looking, in light years, and is what
/// settles which of sixty sectors named `EUQ` are offered.
pub(crate) fn sectors_holding_all(
    words: &[&str],
    near: Option<[f64; 3]>,
    limit: usize,
) -> Vec<(bool, &'static str)> {
    if words.is_empty() || limit == 0 {
        return Vec::new();
    }
    // Where a sector sits, in light years, for ranking by nearness: the
    // key is its coordinates on the galaxy's own grid, so this is
    // arithmetic and not a lookup. Squared, the ordering being the same.
    let away = |key: u32| {
        let Some(near) = near else { return 0.0 };
        let at = sector_of(key);
        (0..3)
            .map(|axis| {
                let middle = elite_journal::boxel::ORIGIN[axis]
                    + f64::from(at[axis]) * elite_journal::boxel::SECTOR_LY
                    + elite_journal::boxel::SECTOR_LY / 2.0;
                (middle - near[axis]).powi(2)
            })
            .sum()
    };
    // Two for a word spelled right and one for a word nearly spelled, so
    // a sector matching both words exactly is offered before one matching
    // both approximately and before one matching a single word. A word
    // matching nothing here is left to the caller, it being a boxel code
    // or a word of a stored name rather than a sector's.
    let mut found: Vec<(usize, u64, &'static str)> = SECTOR_TABLE
        .by_name
        .iter()
        .filter_map(|(sector, key)| {
            let held: usize = words
                .iter()
                .map(|word| {
                    let parts = || sector.split(' ');
                    if parts().any(|part| part.starts_with(*word)) {
                        2
                    } else if parts().any(|part| matches_word(word, part)) {
                        1
                    } else {
                        0
                    }
                })
                .sum();
            (held > 0).then_some((held, away(*key) as u64, *sector))
        })
        .collect();
    // The most words matched first, and the whole list is swept whatever
    // the limit: 11,662 sectors is the vocabulary, and taking the first
    // few that matched one word would answer `EUQ PRAEA` with the sectors
    // alphabetically nearest `PRAEA` rather than with `PRAEA EUQ`.
    // The most words matched first, then the nearest to where the caller
    // is looking, then the name so the answer is the same on every
    // machine. **Nearness is most of what makes this useful**: `EUQ` names
    // sixty-odd sectors and offering them alphabetically answers with
    // whichever the vocabulary happens to begin with, which is nowhere the
    // reader is. With no place to measure from every sector is nought away
    // and the order is the name's, as it was.
    found.sort_unstable_by_key(|(held, away, sector)| {
        (usize::MAX - held, *away, *sector)
    });
    found.truncate(limit);
    // Whether the sector was spelled right, which is the caller's to rank
    // by: a sector merely *near* what was typed is worth less than a
    // stored name that holds the word exactly, and only the caller can
    // weigh the two.
    found
        .into_iter()
        .map(|(held, _, sector)| (held == 2 * words.len(), sector))
        .collect()
}

/// What the words of a query say about a *boxel*
///
/// **The half of a procedural name that is coordinates.** `PRAEA EUQ YE-Q
/// D5-0` is two sector words and then `YE-Q D5-0`, which is not a name to
/// be matched but a position to be read: the three letters are the boxel's
/// coordinates inside its sector in base 26, the letter after them is the
/// mass class, and the numbers are the run and the system's index. A search
/// that matched those as text was searching for a number, which is why
/// `EUQ YE-Q` used to answer nothing while every sector named `EUQ` held a
/// `YE-Q`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(crate) struct Coded {
    /// The boxel's ordinal within its run, from the three letters.
    pub code: u32,
    /// The mass class, where a class letter was typed.
    pub mass: Option<u8>,
    /// The run, where one was written — `D5-0` is run 5 and `D5` is not.
    pub run: Option<u32>,
    /// The system's index in its boxel, where one was typed.
    pub index: Option<u32>,
}

/// Whether `word` is coordinates rather than a name
///
/// The two shapes a tail is written in: `YE-Q`, three letters with a dash
/// before the last, and `D5-0` or `D5`, a mass class and its numbers. A
/// caller matching words against a vocabulary skips these, there being no
/// sector spelled like one.
pub(crate) fn is_coordinate(word: &str) -> bool {
    code_of(word).is_some() || class_of(word).is_some()
}

/// The boxel ordinal three letters spell, `YE-Q` being one.
fn code_of(word: &str) -> Option<u32> {
    let (pair, one) = word.split_once('-')?;
    let (pair, one) = (pair.as_bytes(), one.as_bytes());
    if pair.len() != 2 || one.len() != 1 {
        return None;
    }
    let letter = |b: u8| b.is_ascii_uppercase().then(|| u32::from(b - b'A'));
    Some(letter(pair[0])? + 26 * letter(pair[1])? + 676 * letter(one[0])?)
}

/// The class, run and index a word like `D5-0` spells.
fn class_of(word: &str) -> Option<(u8, Option<u32>, Option<u32>)> {
    let (class, numbers) = word.as_bytes().split_first()?;
    if !class.is_ascii_uppercase() {
        return None;
    }
    let mass = class - b'A';
    if mass > 7 {
        return None;
    }
    let numbers = std::str::from_utf8(numbers).ok()?;
    if numbers.is_empty() {
        return Some((mass, None, None));
    }
    match numbers.split_once('-') {
        // `D5-0`: run five, index nought.
        Some((run, index)) => {
            Some((mass, Some(run.parse().ok()?), Some(index.parse().ok()?)))
        }
        // `D5`: the game writes a run of nought by leaving it out, so this
        // is index five in run nought — and the run is *known*, which is
        // what keeps a query this specific from being enumerated.
        None => Some((mass, Some(0), Some(numbers.parse().ok()?))),
    }
}

/// What `words` say about a boxel, or [`None`] where none of them do
///
/// The code is what makes a query coordinates at all: a class on its own
/// (`D5`) says nothing about *where*, only which of a boxel's systems, so
/// it is read only beside one.
pub(crate) fn coded(words: &[&str]) -> Option<Coded> {
    let code = words.iter().find_map(|word| code_of(word))?;
    let class = words.iter().find_map(|word| class_of(word));
    Some(match class {
        Some((mass, run, index)) => {
            Coded { code, mass: Some(mass), run, index }
        }
        None => Coded { code, ..Coded::default() },
    })
}

/// How many runs of a boxel code a query that named none is tried at.
///
/// A run is the code repeating as a sector fills up, so low runs hold most
/// of what has been reported: the first is every sector's, and a sector
/// deep enough to reach run sixteen is one somebody has surveyed. A query
/// naming a run pays none of this.
const RUNS: u32 = 16;

/// And how many of a boxel's systems, on the same argument: an index past
/// a handful is a boxel with a crowd in it.
const INDICES: u32 = 8;

/// How many addresses a sector is tried at, where the query left the class,
/// the run or the index open
///
/// The enumeration is [`RUNS`] deep by [`INDICES`] wide over eight mass
/// classes, and a sector that holds none of them holds none: this is the
/// bound on what a miss costs, at an address lookup each.
pub(crate) const TRIED: usize = 128;

/// And how many sectors are tried, where the query named a word that
/// several of them hold
///
/// A word like `EUQ` names sixty-odd sectors and every one of them holds a
/// boxel called `YE-Q`, so what bounds this road is how many sectors are
/// worth asking about rather than how many match. Eight nearest the reader,
/// because a coordinate query is about a place: measured over the v4 table,
/// `EUQ YE-Q` answered in 891 ms over twenty-five sectors and 128 ms over
/// eight, and the answers are the eight the reader is nearest.
pub(crate) const TRIED_SECTORS: usize = 8;

/// Every address `coded` could name in the sector `key` stands for, most
/// likely first
///
/// **Construction, not matching.** The address packs the sector, the
/// boxel and the index, so a query that pins all three names exactly one
/// address and the caller has only to ask whether the table holds it. What
/// a query leaves open is enumerated, narrowest first: the mass class it
/// did not say, then the run, then the index — [`RUNS`] and [`INDICES`]
/// deep, which is where the systems anybody has reported are.
///
/// At most `most` of them, and the order is what makes that bound worth
/// having: a caller filling a screenful stops at the first answers rather
/// than the last.
pub(crate) fn addresses_in(key: u32, coded: &Coded, most: usize) -> Vec<i64> {
    let sector = sector_of(key);
    let masses: Vec<u8> = match coded.mass {
        Some(mass) => vec![mass],
        None => (0..8).collect(),
    };
    let runs: Vec<u32> = match coded.run {
        Some(run) => vec![run],
        None => (0..RUNS).collect(),
    };
    let indices: Vec<u32> = match coded.index {
        Some(index) => vec![index],
        None => (0..INDICES).collect(),
    };
    let mut found = Vec::new();
    for index in indices {
        for run in &runs {
            for mass in &masses {
                let Some(ordinal) = elite_journal::boxel::LETTERS
                    .checked_mul(*run)
                    .and_then(|run| coded.code.checked_add(run))
                else {
                    continue;
                };
                let boxel = Boxel { mass: *mass, sector, ordinal, index };
                if let Some(address) = boxel.address() {
                    found.push(address);
                    if found.len() >= most {
                        return found;
                    }
                }
            }
        }
    }
    found
}

/// The sectors nearest `at`, at most `limit`
///
/// What answers a query that is coordinates and nothing else — `YE-Q D5-0`
/// names a boxel of *every* sector, so which sectors are worth trying is
/// the only question, and where the reader is looking is the only answer
/// there is.
pub(crate) fn sectors_near(at: [f64; 3], limit: usize) -> Vec<u32> {
    let away = |key: u32| {
        let sector = sector_of(key);
        (0..3)
            .map(|axis| {
                let middle = elite_journal::boxel::ORIGIN[axis]
                    + f64::from(sector[axis]) * elite_journal::boxel::SECTOR_LY
                    + elite_journal::boxel::SECTOR_LY / 2.0;
                (middle - at[axis]).powi(2)
            })
            .sum::<f64>() as u64
    };
    let mut found: Vec<(u64, u32)> =
        SECTOR_TABLE.by_key.iter().map(|(key, _)| (away(*key), *key)).collect();
    found.sort_unstable();
    found.truncate(limit);
    found.into_iter().map(|(_, key)| key).collect()
}

/// How far a query may be from a sector's name and still be offered.
///
/// Two edits over a *generated* vocabulary is already generous: the
/// procedural names are near neighbours of each other by construction —
/// `EOL PRUA` is a real sector one edit from `EOL PROU`, and both hold
/// systems — so a wide bound answers with plausible places the user did not
/// mean. What keeps that honest is the ranking: the edit distance first,
/// and then how many systems a sector holds, which the caller can weigh
/// against where the camera is looking.
pub const NEAREST: usize = 2;

/// Whether `a` and `b` are within `most` edits, and how many if so.
///
/// Banded Levenshtein: only the `2 * most + 1` diagonals around the main
/// one can hold an answer under the bound, so the work is `most * len`
/// rather than `len * len`, and a row whose whole band is past the bound is
/// a miss — which is what makes sweeping a whole vocabulary cheap. Cells
/// outside the band read as `most + 1`, "further than anybody cares".
fn within(a: &[u8], b: &[u8], most: usize) -> Option<usize> {
    if a.len().abs_diff(b.len()) > most {
        return None;
    }
    if most == 0 {
        return (a == b).then_some(0);
    }
    let far = most + 1;
    let mut prev: Vec<usize> =
        (0..=b.len()).map(|j| if j > most { far } else { j }).collect();
    let mut cur = vec![far; b.len() + 1];
    for (i, ca) in a.iter().enumerate() {
        let from = (i + 1).saturating_sub(most);
        let upto = (i + 1 + most).min(b.len());
        cur[0] = if i + 1 > most { far } else { i + 1 };
        for j in from..=upto {
            if j == 0 {
                continue;
            }
            let swap = prev[j - 1] + usize::from(ca != &b[j - 1]);
            let drop = prev[j] + 1;
            let add = if j > from { cur[j - 1] + 1 } else { far };
            cur[j] = swap.min(drop).min(add).min(far);
        }
        if cur[from..=upto].iter().all(|held| *held >= far) {
            return None;
        }
        std::mem::swap(&mut prev, &mut cur);
        cur.fill(far);
    }
    (prev[b.len()] <= most).then_some(prev[b.len()])
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The dictionary parses, and holds what it was generated with.
    #[test]
    fn the_dictionary_is_read() {
        assert_eq!(sector_count(), 11_662);
        // Every name is unique, which the by-name search depends on: a
        // region claiming several coordinates is left out of the file, so
        // no two keys share a name.
        let held = &*SECTOR_TABLE;
        for pair in held.by_name.windows(2) {
            assert_ne!(pair[0].0, pair[1].0, "two sectors share a name");
        }
        // The file is `key,name` with no quoting, which is only sound
        // because a generated sector name is letters, digits and spaces.
        // A name holding a comma would have split its row in half at the
        // parse and been read as a shorter one, silently.
        for (name, _) in &held.by_name {
            assert!(
                name.bytes().all(|byte| byte.is_ascii_uppercase()
                    || byte.is_ascii_digit()
                    || byte == b' '),
                "{name} is not the character set the file's format assumes",
            );
        }
        for pair in held.by_key.windows(2) {
            assert!(pair[0].0 < pair[1].0, "the keys are not sorted");
        }
    }

    /// A known system's name comes back from its address alone.
    ///
    /// Three from `.index/full`, one per shape: a one-word sector whose
    /// run is nought and therefore unwritten, and two with a run. The
    /// arithmetic itself is `elite_journal::Boxel`'s to hold; what these
    /// pin is the dictionary joined onto it.
    #[test]
    fn a_name_is_spelled_from_its_address() {
        for (address, name) in [
            (96_076_086, "SIDGIO AA-A G1"),
            (1_038_034_644, "PRUE EAEWSY NR-W E1-0"),
            (1_189_102_764, "WREDGEOU TO-R E4-0"),
        ] {
            assert_eq!(
                name_of(address).map(String::from),
                Some(name.to_owned()),
                "{address}",
            );
            assert_eq!(address_of(name), Some(address), "{name}");
        }
    }

    /// A sector's key goes round, so the dictionary is keyed by what it is
    /// looked up by.
    #[test]
    fn a_sector_key_is_its_coordinates() {
        for sector in [[0, 0, 0], [127, 63, 127], [39, 32, 18], [1, 2, 3]] {
            assert_eq!(sector_of(sector_key(sector)), sector, "{sector:?}");
        }
        // And the name a key holds is the name that finds it.
        let (key, name) = sectors().next().expect("a sector");
        assert_eq!(sector_named(name).map(sector_key), Some(key));
    }

    /// Nothing procedural is claimed for a name that is not.
    #[test]
    fn a_given_name_spells_no_address() {
        for name in [
            "SOL",
            "HD 225160",
            "CYGNI X-3",
            // A hand-authored region: left out of the dictionary on
            // purpose, since its boxels are numbered from its own origin.
            "COL 285 SECTOR YE-Q D5-0",
            "PRAEA EUQ YE-Q D5",
            "PRAEA EUQ YE-Q Z5-0",
        ] {
            assert_eq!(address_of(name), None, "{name}");
        }
    }

    /// A word is coordinates or it is a name, and the difference is read
    ///
    /// **What lets a query be constructed rather than matched.** The code
    /// is the boxel's ordinal in base 26 and the class carries the run and
    /// the index, so a query naming all three names one address; a word
    /// that is a name is left to the vocabulary.
    #[test]
    fn a_coordinate_word_is_told_from_a_name() {
        // The code alone leaves the class, the run and the index open.
        assert_eq!(
            coded(&["EUQ", "YE-Q"]),
            Some(Coded { code: code_of("YE-Q").unwrap(), ..Coded::default() }),
        );
        // `D5-0` is run five, index nought; `D5` is the run left out,
        // which is run nought and index five.
        let code = code_of("YE-Q").unwrap();
        assert_eq!(
            coded(&["YE-Q", "D5-0"]),
            Some(Coded { code, mass: Some(3), run: Some(5), index: Some(0) }),
        );
        assert_eq!(
            coded(&["YE-Q", "D5"]),
            Some(Coded { code, mass: Some(3), run: Some(0), index: Some(5) }),
        );

        // A class on its own says nothing about *where*, only which of a
        // boxel's systems, so it is read beside a code and not instead of
        // one.
        assert_eq!(coded(&["D5-0"]), None);
        assert_eq!(coded(&["PRAEA", "EUQ"]), None);
        // And a class past `H` is no class at all.
        assert_eq!(
            coded(&["YE-Q", "Z5-0"]),
            Some(Coded { code, ..Coded::default() })
        );

        assert!(is_coordinate("YE-Q"));
        assert!(is_coordinate("D5-0"));
        assert!(!is_coordinate("PRAEA"));
        assert!(!is_coordinate("SOL"));
    }

    /// The addresses a coded query names are built, and the narrowest is one
    #[test]
    fn a_coded_query_builds_its_addresses() {
        let key = sector_key(Boxel::of(1_038_034_644).sector);
        let pinned = coded(&["NR-W", "E1-0"]).expect("coordinates");
        assert_eq!(addresses_in(key, &pinned, TRIED), [1_038_034_644]);

        // With the class left open every class is tried, and the address
        // each yields spells the tail back.
        let open = coded(&["NR-W"]).expect("coordinates");
        let built = addresses_in(key, &open, TRIED);
        assert!(built.len() > 8, "{}", built.len());
        assert!(built.contains(&1_038_034_644), "{built:?}");
        for address in built {
            assert_eq!(name_of(address).is_some(), true, "{address}");
        }
    }

    /// An address whose sector nobody has named spells nothing.
    #[test]
    fn an_unnamed_sector_spells_nothing() {
        // Sector (0, 0, 0) is the far corner of the grid and holds nothing.
        let boxel = Boxel { mass: 0, sector: [0, 0, 0], ordinal: 0, index: 0 };
        let address = boxel.address().expect("an address");
        assert_eq!(name_of(address), None);
    }
}
