[package]
name    = "galos"
version = "0.0.1-dev+alpha"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
edition = "2018"

default-run = "galos"

[[bin]]
name = "galos"
path = "src/bin/galos/main.rs"

[[target.'cfg(unix)'.bin]]
name = "galos-sync"
path = "src/bin/galos-sync/main.rs"

[dependencies]
async-std = "*"
structopt = "*"
itertools = "*"
indicatif = "*"

# Subcomponents of Galos.
galos_db     = { path = 'galos_db' }
galos-gui    = { path = 'galos-gui' }
# galos_server = { path = 'galos-server' }
# galos-worker  = { path = 'galos-worker' }


# Our open source crates.
# elite_dat = { path = './elite_dat' }
elite_journal = { git = "https://github.com/ED-NEWP/elite_journal" }
eddn          = { git = "https://github.com/ED-NEWP/eddn" }
eddb          = { git = "https://github.com/ED-NEWP/eddb" }
edsm          = { git = "https://github.com/ED-NEWP/edsm" }

[target.'cfg(unix)'.dependencies]
prettytable-rs = "*"
termion = "*"
tui = "*"


# TODO
# [patch.'https://github.com/ED-NEWP/elite_dat']
# elite_dat = { path = './elite_dat' }

[patch.'https://github.com/ED-NEWP/elite_journal']
elite_journal = { path = './elite_journal' }

[patch.'https://github.com/ED-NEWP/eddn']
eddn = { path = './eddn' }

[patch.'https://github.com/ED-NEWP/eddb']
eddb = { path = './eddb' }

[patch.'https://github.com/ED-NEWP/edsm']
edsm = { path = './edsm' }

[workspace]
members = [
    # "elite_dat",
    "elite_journal",
    "eddn",
    "eddb",
    "edsm",
    "galos_db",
    # "galos-gui",
    # "galos-server",
    # "galos-worker",
]
