[package]
name    = "galos"
version = "0.0.2"
authors = ["Nathan Lilienthal <nathan@nixpulvis.com>"]
edition = "2018"

default-run = "galos"

[dependencies]
async-std = "*"
structopt = "*"
itertools = "*"
indicatif = "*"
chrono = "*"

# Subcomponents of Galos.
galos_db  = { path = 'galos_db' }
# galos-gui     = { path = 'galos-gui' }
# galos-server  = { path = 'galos-server' }
# galos-worker  = { path = 'galos-worker' }


# Our open source crates.
# elite_dat = { path = './elite_dat' }
elite_journal = { path = "./elite_journal" }
eddn          = { path = "./eddn" }
eddb          = { path = "./eddb" }
edsm          = { path = "./edsm" }

[target.'cfg(unix)'.dependencies]
prettytable-rs = "*"
termion = "*"
tui = "*"


# TODO
# [patch.'https://github.com/nixpulvis/elite_dat']
# elite_dat = { path = './elite_dat' }

[patch.crates-io]
elite_journal = { path = './elite_journal' }
# eddn = { path = './eddn' }

# [patch.'https://github.com/nixpulvis/eddb']
# eddb = { path = './eddb' }

# [patch.'https://github.com/nixpulvis/edsm']
# edsm = { path = './edsm' }

[workspace]
members = [
    # "elite_dat",
    "elite_journal",
    "eddn",
    "eddb",
    "edsm",
    "galos_db",
    # "galos-gui",
    # "galos-server",
    # "galos-worker",
]
