[package]
name = "starmap"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "*", features = ["shader_format_glsl"] }
rand = "*"
rand_chacha = "*"
async-std = "*"
galos_db = { path = "../galos_db" }
