[package]
name = "galos_map"
version = "0.1.0"
edition = "2024"

[features]
inspector = ["bevy-inspector-egui"]
tracy = ["bevy/trace_tracy"]

[dependencies]
async-std = "*"
bevy = "0.19"
bevy-inspector-egui = { version = "0.37", optional = true }
bevy_egui = "0.40"
bevy_panorbit_camera = { version = "0.35", features = ["bevy_egui"] }
bevy_rich_text3d = "0.7"
chrono = "*"
elite_journal = { path = "../elite_journal" }
galos_db = { path = "../galos_db" }
