//! The names the galaxy does not have to store.
//!
//! **97.3 % of a galaxy's system names are a function of the system's
//! address.** Measured over `.index/full` — 200,071,629 names — 194,667,563
//! of them are spelled exactly by the arithmetic here plus the sector
//! dictionary beside it. A name that agrees with what this derives does not
//! have to be written down at all: `text.bin` holds 3.94 GB of names and
//! 136 MB of them are names this cannot spell.
//!
//! ## What an address carries
//!
//! [`elite_journal::Boxel`] holds that half: a `SystemAddress` packs the
//! system's mass class, its sector on the galaxy's 1,280 ly grid, the
//! boxel inside that sector and the system's index inside the boxel, and a
//! procedural name spells the same place back — `PRAEA EUQ YE-Q D5-0`. The
//! layout and the spelling are facts about the game and are written down
//! there, beside the events they arrive in.
//!
//! What is here is the other half, which is *not* a fact about the game:
//! **the sector's name**. Frontier generates it, and no arithmetic in this
//! crate reproduces the generator — so the dictionary is **learned** from a
//! galaxy somebody imported (`galos-index sectors`) and compiled in. 11,662
//! sectors, 192 KB, and the join of the two halves is [`name_of`].
//!
//! ## What it cannot spell, and why that is safe
//!
//! Two populations, both measured:
//!
//! - **Names people gave** — 151,463 of them, `HD 225160`, `CYGNI X-3`.
//!   They are not procedural and nothing here claims them.
//! - **Frontier's hand-authored regions** — `COL 285 SECTOR`, `IC 2944
//!   SECTOR`, the nebulae: 5,252,594 rows. A region is a sphere laid over
//!   the grid, spanning up to eight sectors, and its boxels are numbered
//!   from the region's own origin rather than the grid's. So [`sector`]
//!   deliberately **does not hold them**: a name that claimed more than one
//!   sector coordinate is left out of the dictionary, and every system
//!   under one is stored.
//!
//! Which is what makes the scheme safe rather than clever: the caller
//! derives a name, compares it with the one reported, and stores the name
//! whenever the two differ. A derivation that is wrong is a name that gets
//! written down, not a name that gets lost. And a system whose name arrives
//! later is one stored name over a derived one, which is the overlay this
//! table already has.

use crate::SystemName;
use elite_journal::Boxel;
use std::sync::LazyLock;

/// The sector dictionary: a packed sector coordinate and the name of it.
///
/// Generated by `galos-index sectors` from a built directory, and compiled
/// in rather than published: it is 11,662 sectors and 192 KB, it is the
/// same for every galaxy, and a derivation that needed a file could not be
/// done by a database writer with no index directory to read.
///
/// Sorted by key, which is what makes the parse below a sorted vector
/// without a sort. A plain `key,name` a line and no quoting: every sector
/// name Frontier generates is `[A-Z0-9 ]` — measured over all 11,662, no
/// commas and no quotes — and `the_dictionary_is_read` asserts that, so a
/// name that ever arrived with a comma in it would fail the test rather
/// than split a row in half.
const SECTORS: &str = include_str!("../data/sectors.csv");

/// How many bits of the key each sector axis takes: x and z reach 127, y
/// reaches 63, which is the galaxy's own grid.
const SECTOR_BITS: [u32; 3] = [7, 6, 7];

/// A sector's coordinates as one number, which is how the dictionary keys
/// them.
///
/// This crate's own encoding rather than anything the game writes — twenty
/// bits of the grid, packed x, y, z — so it lives here with the file it
/// keys and not beside [`Boxel`], which holds only what an address says.
pub fn sector_key(sector: [u8; 3]) -> u32 {
    (u32::from(sector[0]) << (SECTOR_BITS[1] + SECTOR_BITS[2]))
        | (u32::from(sector[1]) << SECTOR_BITS[2])
        | u32::from(sector[2])
}

/// The sector coordinates a [`sector_key`] stands for.
fn sector_of(key: u32) -> [u8; 3] {
    [
        (key >> (SECTOR_BITS[1] + SECTOR_BITS[2])) as u8,
        ((key >> SECTOR_BITS[2]) & 0x3F) as u8,
        (key & 0x7F) as u8,
    ]
}

/// The dictionary, parsed once off the text compiled into the binary.
struct Sectors {
    /// Every sector, by key, in the file's own ascending order.
    by_key: Vec<(u32, &'static str)>,
    /// The same rows by name, for resolving a name to an address.
    by_name: Vec<(&'static str, u32)>,
}

/// The sector dictionary, parsed on the first ask.
///
/// Two sorted vectors over the compiled-in text: nothing is copied, the
/// names being `&'static str` into the binary itself, and 11,662 rows is
/// tens of microseconds to parse. A `HashMap` would cost the same lookups
/// an allocation apiece to build and lose the by-name order a search wants.
static SECTOR_TABLE: LazyLock<Sectors> = LazyLock::new(|| {
    let mut by_key: Vec<(u32, &'static str)> = SECTORS
        .lines()
        .filter_map(|line| {
            let (key, name) = line.split_once(',')?;
            Some((key.parse().ok()?, name))
        })
        .collect();
    by_key.sort_unstable_by_key(|(key, _)| *key);
    let mut by_name: Vec<(&'static str, u32)> =
        by_key.iter().map(|(key, name)| (*name, *key)).collect();
    by_name.sort_unstable();
    Sectors { by_key, by_name }
});

/// How many sectors the dictionary holds.
pub fn sector_count() -> usize {
    SECTOR_TABLE.by_key.len()
}

/// Every sector the dictionary holds, by key, ascending.
///
/// For whoever is regenerating the file: the one property it has to keep is
/// that an entry is added and never changed or dropped, since a name was
/// left unwritten because this spelled it. See `galos-index sectors`.
pub fn sectors() -> impl Iterator<Item = (u32, &'static str)> {
    SECTOR_TABLE.by_key.iter().copied()
}

/// The name of the sector at `key`, or [`None`] where none is known.
///
/// [`None`] is the ordinary answer for unexplored space and for the
/// hand-authored regions, which are deliberately absent — see the module
/// header.
pub fn sector_at(key: u32) -> Option<&'static str> {
    let held = &*SECTOR_TABLE;
    held.by_key
        .binary_search_by_key(&key, |(key, _)| *key)
        .ok()
        .map(|at| held.by_key[at].1)
}

/// The sector coordinates of the sector named `name`, upper case.
pub fn sector_named(name: &str) -> Option<[u8; 3]> {
    let held = &*SECTOR_TABLE;
    let at =
        held.by_name.binary_search_by_key(&name, |(name, _)| *name).ok()?;
    Some(sector_of(held.by_name[at].1))
}

/// The name `address` spells, or [`None`] where nothing spells it.
///
/// [`None`] where the address's sector is not in the dictionary, which is
/// unexplored space and every hand-authored region. A caller comparing this
/// against a reported name gets the whole rule: equal, and the name need
/// not be stored; anything else, and it must be.
pub fn name_of(address: i64) -> Option<SystemName> {
    let boxel = Boxel::of(address);
    let sector = sector_at(sector_key(boxel.sector))?;
    // `new` takes the string it is handed and folds it in place, and the
    // pieces are upper already, so this is the one allocation the format
    // itself needs and no copy on top of it.
    Some(SystemName::new(format!("{sector} {}", boxel.tail())))
}

/// The address `name` spells, or [`None`] where it spells none.
///
/// The inverse of [`name_of`], which is what makes a name resolvable
/// without a table: a procedural name carries its own address. Checked
/// rather than assumed — [`Boxel::address`] refuses a name spelling
/// coordinates no address holds — and confirmed by round-tripping it, so a
/// name that resolves here resolves to the system that bears it.
pub fn address_of(name: &str) -> Option<i64> {
    let (head, last) = name.rsplit_once(' ')?;
    let (sector, code) = head.rsplit_once(' ')?;
    let at = sector_named(sector)?;
    let boxel = Boxel::spelled(&format!("{code} {last}"), at)?;
    let address = boxel.address()?;
    // The one check that makes this safe to answer a lookup with: the
    // address has to spell the name back.
    (Boxel::of(address) == boxel).then_some(address)
}

/// Whether `name` is what [`name_of`] spells for `address`.
///
/// The question a writer asks before storing a name.
pub fn spells(address: i64, name: &str) -> bool {
    name_of(address).is_some_and(|held| held == *name)
}

/// Which sectors hold a word beginning with `needle`, at most `limit`.
///
/// The mid-name half of a search over *derived* names, and the reason it
/// costs nothing: a derived name is a sector and a boxel code, so the only
/// word in it anybody types is in this dictionary — 11,662 names and 192
/// KB, compiled in and swept in microseconds. What a caller does with a
/// sector is walk its run of the by-name order, the sector being what a
/// procedural name begins with.
///
/// A word start rather than any offset, for [`crate::names`]'s reason:
/// matching mid-word would answer `EUQ` with every sector merely holding
/// those letters.
pub fn sectors_holding(needle: &str, limit: usize) -> Vec<&'static str> {
    if needle.is_empty() || limit == 0 {
        return Vec::new();
    }
    SECTOR_TABLE
        .by_name
        .iter()
        .filter(|(sector, _)| {
            sector.split(' ').any(|word| word.starts_with(needle))
        })
        .map(|(sector, _)| *sector)
        .take(limit)
        .collect()
}

/// How many letters of a *word* may be wrong before it says nothing
///
/// [`EXACTLY_UNDER`] is about a whole sector name; a word of one is three
/// to six letters, and the bound has to be read against that length or it
/// answers with the vocabulary. One edit on three letters reaches a quarter
/// of the alphabet — `EQU` is one from `EQ-G`, `ECU`, `EQZ` — so three
/// letters are matched exactly and the slack opens with the word:
///
/// | letters | edits |
/// |---|---|
/// | under four | 0 |
/// | four or five | 1 |
/// | six or more | [`NEAREST`] |
pub fn slack(word: &str) -> usize {
    match word.len() {
        0..=3 => 0,
        4..=5 => 1,
        _ => NEAREST,
    }
}

/// Whether `word` matches `held`: at its start, or near enough
///
/// The one rule a query's word is matched by, wherever it is matched — the
/// sector vocabulary here, and the rows a caller sieves behind it. A prefix
/// counts because that is what a search is; the edits are [`slack`]'s.
pub fn matches_word(word: &str, held: &str) -> bool {
    held.starts_with(word)
        || within(word.as_bytes(), held.as_bytes(), slack(word)).is_some()
}

/// The sectors holding the most of `words`, the most first, at most `limit`
///
/// **What answers a query whose words are out of order.** A derived name is
/// a sector and then coordinates, so a reader typing `EUQ PRAEA` — or the
/// sector of a place they have been and the boxel code off a screenshot —
/// is naming the sector in pieces. A sector matching two of the words is
/// offered before one matching a single word, and a word that matches no
/// sector at all is left to the caller to check against the coordinates.
///
/// `near` is where the reader is looking, in light years, and is what
/// settles which of sixty sectors named `EUQ` are offered.
pub fn sectors_holding_all(
    words: &[&str],
    near: Option<[f64; 3]>,
    limit: usize,
) -> Vec<&'static str> {
    if words.is_empty() || limit == 0 {
        return Vec::new();
    }
    // Where a sector sits, in light years, for ranking by nearness: the
    // key is its coordinates on the galaxy's own grid, so this is
    // arithmetic and not a lookup. Squared, the ordering being the same.
    let away = |key: u32| {
        let Some(near) = near else { return 0.0 };
        let at = sector_of(key);
        (0..3)
            .map(|axis| {
                let middle = elite_journal::boxel::ORIGIN[axis]
                    + f64::from(at[axis]) * elite_journal::boxel::SECTOR_LY
                    + elite_journal::boxel::SECTOR_LY / 2.0;
                (middle - near[axis]).powi(2)
            })
            .sum()
    };
    // Two for a word spelled right and one for a word nearly spelled, so
    // a sector matching both words exactly is offered before one matching
    // both approximately and before one matching a single word. A word
    // matching nothing here is left to the caller, it being a boxel code
    // or a word of a stored name rather than a sector's.
    let mut found: Vec<(usize, u64, &'static str)> = SECTOR_TABLE
        .by_name
        .iter()
        .filter_map(|(sector, key)| {
            let held: usize = words
                .iter()
                .map(|word| {
                    let parts = || sector.split(' ');
                    if parts().any(|part| part.starts_with(*word)) {
                        2
                    } else if parts().any(|part| matches_word(word, part)) {
                        1
                    } else {
                        0
                    }
                })
                .sum();
            (held > 0).then_some((held, away(*key) as u64, *sector))
        })
        .collect();
    // The most words matched first, and the whole list is swept whatever
    // the limit: 11,662 sectors is the vocabulary, and taking the first
    // few that matched one word would answer `EUQ PRAEA` with the sectors
    // alphabetically nearest `PRAEA` rather than with `PRAEA EUQ`.
    // The most words matched first, then the nearest to where the caller
    // is looking, then the name so the answer is the same on every
    // machine. **Nearness is most of what makes this useful**: `EUQ` names
    // sixty-odd sectors and offering them alphabetically answers with
    // whichever the vocabulary happens to begin with, which is nowhere the
    // reader is. With no place to measure from every sector is nought away
    // and the order is the name's, as it was.
    found.sort_unstable_by_key(|(held, away, sector)| {
        (usize::MAX - held, *away, *sector)
    });
    found.truncate(limit);
    found.into_iter().map(|(.., sector)| sector).collect()
}

/// How far a query may be from a sector's name and still be offered.
///
/// Two edits over a *generated* vocabulary is already generous: the
/// procedural names are near neighbours of each other by construction —
/// `EOL PRUA` is a real sector one edit from `EOL PROU`, and both hold
/// systems — so a wide bound answers with plausible places the user did not
/// mean. What keeps that honest is the ranking: the edit distance first,
/// and then how many systems a sector holds, which the caller can weigh
/// against where the camera is looking.
pub const NEAREST: usize = 2;

/// Below this many characters a query is matched exactly.
///
/// One edit on three letters reaches a quarter of the alphabet's worth of
/// sectors and says nothing about which was meant.
pub const EXACTLY_UNDER: usize = 5;

/// A sector a query nearly spells.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Near {
    /// How many edits from the query, nought being exactly it.
    pub edits: usize,
    /// The sector's name.
    pub sector: &'static str,
    /// Its key, for [`sector_at`]'s side of the table.
    pub key: u32,
}

/// The sectors `query` nearly spells, nearest first, at most `limit`.
///
/// **The whole point of deriving names is that this is small.** A galaxy's
/// 200 M names hold only 11,662 distinct sectors — 192 KB, compiled in and
/// resident — so a fuzzy match is a sweep of the vocabulary rather than of
/// the galaxy, with no prefilter and no index. Everything else about a
/// procedural name is coordinates, which are parsed rather than matched.
///
/// `most` is the edit bound, clamped to [`NEAREST`]; a query shorter than
/// [`EXACTLY_UNDER`] is matched exactly whatever is asked for. Ties are
/// broken by name so the answer is the same on every machine.
pub fn sectors_like(query: &str, most: usize, limit: usize) -> Vec<Near> {
    let most = if query.len() < EXACTLY_UNDER { 0 } else { most.min(NEAREST) };
    let mut found: Vec<Near> = SECTOR_TABLE
        .by_name
        .iter()
        .filter_map(|(sector, key)| {
            within(query.as_bytes(), sector.as_bytes(), most)
                .map(|edits| Near { edits, sector, key: *key })
        })
        .collect();
    found.sort_unstable_by_key(|near| (near.edits, near.sector));
    found.truncate(limit);
    found
}

/// The names `query` nearly spells, nearest first, at most `limit`.
///
/// A procedural name is a sector and then coordinates, and only the sector
/// can be misspelled: the tail has to *parse*, because a wrong letter there
/// is a different boxel rather than a near miss. So this fuzzes the words
/// and keeps the tail exactly, and answers a name with the address that
/// bears it.
///
/// **An address it answers with is a place, not a promise.** Every boxel
/// has an address whether or not a system was ever reported in it, so the
/// caller still has to ask the table or the index whether the system
/// exists — which is what a search does anyway to draw it.
pub fn names_like(
    query: &str,
    most: usize,
    limit: usize,
) -> Vec<(usize, SystemName, i64)> {
    let Some((head, last)) = query.rsplit_once(' ') else { return Vec::new() };
    let Some((sector, code)) = head.rsplit_once(' ') else { return Vec::new() };
    let tail = format!("{code} {last}");
    sectors_like(sector, most, limit)
        .into_iter()
        .filter_map(|near| {
            let boxel = Boxel::spelled(&tail, sector_of(near.key))?;
            let address = boxel.address()?;
            let name =
                SystemName::new(format!("{} {}", near.sector, boxel.tail()));
            (Boxel::of(address) == boxel).then_some((near.edits, name, address))
        })
        .collect()
}

/// Whether `query` is within `most` edits of `word`, and how many if so
///
/// The same bound the sector search uses, for a caller sieving rows behind
/// it: a fuzzy road whose sieve was exact would throw away every row it
/// just found. See [`within`].
pub fn near(query: &str, word: &str, most: usize) -> Option<usize> {
    within(query.as_bytes(), word.as_bytes(), most)
}

/// Whether `a` and `b` are within `most` edits, and how many if so.
///
/// Banded Levenshtein: only the `2 * most + 1` diagonals around the main
/// one can hold an answer under the bound, so the work is `most * len`
/// rather than `len * len`, and a row whose whole band is past the bound is
/// a miss — which is what makes sweeping a whole vocabulary cheap. Cells
/// outside the band read as `most + 1`, "further than anybody cares".
fn within(a: &[u8], b: &[u8], most: usize) -> Option<usize> {
    if a.len().abs_diff(b.len()) > most {
        return None;
    }
    if most == 0 {
        return (a == b).then_some(0);
    }
    let far = most + 1;
    let mut prev: Vec<usize> =
        (0..=b.len()).map(|j| if j > most { far } else { j }).collect();
    let mut cur = vec![far; b.len() + 1];
    for (i, ca) in a.iter().enumerate() {
        let from = (i + 1).saturating_sub(most);
        let upto = (i + 1 + most).min(b.len());
        cur[0] = if i + 1 > most { far } else { i + 1 };
        for j in from..=upto {
            if j == 0 {
                continue;
            }
            let swap = prev[j - 1] + usize::from(ca != &b[j - 1]);
            let drop = prev[j] + 1;
            let add = if j > from { cur[j - 1] + 1 } else { far };
            cur[j] = swap.min(drop).min(add).min(far);
        }
        if cur[from..=upto].iter().all(|held| *held >= far) {
            return None;
        }
        std::mem::swap(&mut prev, &mut cur);
        cur.fill(far);
    }
    (prev[b.len()] <= most).then_some(prev[b.len()])
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The dictionary parses, and holds what it was generated with.
    #[test]
    fn the_dictionary_is_read() {
        assert_eq!(sector_count(), 11_662);
        // Every name is unique, which the by-name search depends on: a
        // region claiming several coordinates is left out of the file, so
        // no two keys share a name.
        let held = &*SECTOR_TABLE;
        for pair in held.by_name.windows(2) {
            assert_ne!(pair[0].0, pair[1].0, "two sectors share a name");
        }
        // The file is `key,name` with no quoting, which is only sound
        // because a generated sector name is letters, digits and spaces.
        // A name holding a comma would have split its row in half at the
        // parse and been read as a shorter one, silently.
        for (name, _) in &held.by_name {
            assert!(
                name.bytes().all(|byte| byte.is_ascii_uppercase()
                    || byte.is_ascii_digit()
                    || byte == b' '),
                "{name} is not the character set the file's format assumes",
            );
        }
        for pair in held.by_key.windows(2) {
            assert!(pair[0].0 < pair[1].0, "the keys are not sorted");
        }
    }

    /// A known system's name comes back from its address alone.
    ///
    /// Three from `.index/full`, one per shape: a one-word sector whose
    /// run is nought and therefore unwritten, and two with a run. The
    /// arithmetic itself is `elite_journal::Boxel`'s to hold; what these
    /// pin is the dictionary joined onto it.
    #[test]
    fn a_name_is_spelled_from_its_address() {
        for (address, name) in [
            (96_076_086, "SIDGIO AA-A G1"),
            (1_038_034_644, "PRUE EAEWSY NR-W E1-0"),
            (1_189_102_764, "WREDGEOU TO-R E4-0"),
        ] {
            assert_eq!(
                name_of(address).map(String::from),
                Some(name.to_owned()),
                "{address}",
            );
            assert_eq!(address_of(name), Some(address), "{name}");
        }
    }

    /// A sector's key goes round, so the dictionary is keyed by what it is
    /// looked up by.
    #[test]
    fn a_sector_key_is_its_coordinates() {
        for sector in [[0, 0, 0], [127, 63, 127], [39, 32, 18], [1, 2, 3]] {
            assert_eq!(sector_of(sector_key(sector)), sector, "{sector:?}");
        }
        // And the name a key holds is the name that finds it.
        let (key, name) = sectors().next().expect("a sector");
        assert_eq!(sector_named(name).map(sector_key), Some(key));
    }

    /// Nothing procedural is claimed for a name that is not.
    #[test]
    fn a_given_name_spells_no_address() {
        for name in [
            "SOL",
            "HD 225160",
            "CYGNI X-3",
            // A hand-authored region: left out of the dictionary on
            // purpose, since its boxels are numbered from its own origin.
            "COL 285 SECTOR YE-Q D5-0",
            "PRAEA EUQ YE-Q D5",
            "PRAEA EUQ YE-Q Z5-0",
        ] {
            assert_eq!(address_of(name), None, "{name}");
        }
    }

    /// An address whose sector nobody has named spells nothing.
    #[test]
    fn an_unnamed_sector_spells_nothing() {
        // Sector (0, 0, 0) is the far corner of the grid and holds nothing.
        let boxel = Boxel { mass: 0, sector: [0, 0, 0], ordinal: 0, index: 0 };
        let address = boxel.address().expect("an address");
        assert_eq!(name_of(address), None);
    }

    /// A misspelled sector is offered the one that was meant
    ///
    /// Real sectors, off `.index/full`, with the mistakes people make: a
    /// dropped letter, a transposition, a doubled one.
    #[test]
    fn a_misspelled_sector_is_found() {
        let named = |query: &str| -> Vec<(usize, &'static str)> {
            sectors_like(query, NEAREST, 4)
                .into_iter()
                .map(|near| (near.edits, near.sector))
                .collect()
        };

        // Exactly right comes back at no edits, and first.
        assert_eq!(named("EOL PROU")[0], (0, "EOL PROU"));
        // A letter dropped, and a transposition.
        assert!(
            named("EOL PRU").contains(&(1, "EOL PROU")),
            "{:?}",
            named("EOL PRU")
        );
        assert!(
            named("PREA EUQ").contains(&(1, "PRAEA EUQ")),
            "{:?}",
            named("PREA EUQ"),
        );
        // A doubled letter in a one-word sector.
        assert!(named("SIDGIIO").contains(&(1, "SIDGIO")));

        // Nothing within the bound is nothing offered, rather than the
        // nearest thing whatever it costs.
        assert!(named("ZZZZZZZZZZ").is_empty());

        // And a short query is exact, however wide a bound is asked for: a
        // stray letter in four would answer with a swathe of the sky.
        // `AEMO` is a real sector and `CUQE` is its neighbour in the file,
        // one edit from `CUQI`, `CUQO` and `CUQU` — none of which is
        // offered.
        assert_eq!(named("AEMO"), [(0, "AEMO")]);
        assert_eq!(named("CUQE"), [(0, "CUQE")]);
        assert!(named("CUQ").is_empty());
    }

    /// A misspelled name is offered the system it nearly spells
    ///
    /// The sector is fuzzed and the tail is not: a wrong letter in `YE-Q
    /// D5-0` is a different boxel, not a near miss, so it has to parse.
    #[test]
    fn a_misspelled_name_is_offered_its_system() {
        let found = names_like("PRUE EAEWSY NR-W E1-0", NEAREST, 4);
        assert_eq!(found[0].0, 0, "{found:?}");
        assert_eq!(found[0].1, SystemName::new("PRUE EAEWSY NR-W E1-0"));
        assert_eq!(found[0].2, 1_038_034_644);

        // A dropped letter in the sector still lands on the system.
        let found = names_like("PRUE EAEWSY NR-W E1-0", NEAREST, 4);
        let slipped = names_like("PRUE EAEWS NR-W E1-0", NEAREST, 4);
        assert!(
            slipped.iter().any(|(edits, name, address)| {
                *edits == 1 && *name == found[0].1 && *address == found[0].2
            }),
            "{slipped:?}",
        );

        // A tail that does not parse is not a near miss of anything.
        assert!(names_like("PRUE EAEWSY NR-W Z1-0", NEAREST, 4).is_empty());
        assert!(names_like("SOL", NEAREST, 4).is_empty());
    }
}
